### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ilovepackets** [Aetheam/SimpleCustomTPA#1]
PocketMine-MP Crash Dump Mon Mar 7 00:30:50 EST 2022

Error: Call to a member function cancel() on null
File: plugins/SimpleCustomTPA_dev-7.phar/src/achedon/customtpa/tasks/delay
Line: 31
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: customTPA

Code:
[22]         if($this->time == 0){
[23]             if(isset(tpa::$REQUEST[$this->player->getName()])){
[24]                 $this->player->sendMessage(messageManager::message("You request have been deleted"));
[25]                 var_dump($this->time);
[26]                 unset(tpa::$REQUEST[$this->player->getName()]);
[27]                 $this->getHandler()->cancel();
[28]             }
[29]         }
[30]         if(!isset(tpa::$REQUEST[$this->player->getName()])){
[31]             $this->getHandler()->cancel();
[32]         }
[33]         $this->time--;
[34]     }
[35] }

Backtrace:
#0 pmsrc/src/scheduler/TaskHandler(117): achedon\customtpa\tasks\delay->onRun()
#1 pmsrc/src/scheduler/TaskScheduler(141): pocketmine\scheduler\TaskHandler->run()
#2 pmsrc/src/plugin/PluginManager(466): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 3085)
#3 pmsrc/src/Server(1768): pocketmine\plugin\PluginManager->tickSchedulers(integer 3085)
#4 pmsrc/src/Server(1657): pocketmine\Server->tick()
#5 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
#6 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[51] /home/gameserver/servers/serveur3/minecraftbedrock/, string[59] /home/gameserver/servers/serveur3/minecraftbedrock/plugins/)
#7 pmsrc/src/PocketMine(327): pocketmine\server()
#8 pmsrc(11): require(string[95] phar:///home/gameserver/servers/serveur3/minecraftbedrock/PocketMine-MP.phar/src)

PocketMine-MP version: 4.2.2 [Protocol 486]
Git commit: 12946fbe466335ccf9d94f63a65400903c924fca
uname -a: Linux game-useast-03.mtxserv.com 5.4.125-mtxserv #1 SMP PREEMPT Mon Jun 14 17:57:17 CEST 2021 x86_64
PHP Version: 8.0.13
Zend version: 4.0.13
OS: Linux, linux
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.6.0+bedrock-1.18.10@e98c511584a7bd58a95986374d2df4b04c6a2ba0
- pocketmine/bedrock-protocol 8.0.0+bedrock-1.18.10@017e57c8f8a74118bcbba7332e7ebac9e6c81693
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.4.3@4d0b081f1a79407e087968ea76aaf330db6ea2b5
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.2.2@12946fbe466335ccf9d94f63a65400903c924fca
- pocketmine/raklib 0.14.3@4798576fec0364266dce23b368a7fec5e5de7927
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.24.0@30885182c981ab175d4d034db0f6f469898070ab
- symfony/polyfill-php80 v1.24.0@57b712b08eddb97c762a8caa32c84e037892d2e9
- symfony/polyfill-php81 v1.24.0@5de4ba2d41b15f9bd0e19b2ab9674135813ec98f
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725

Loaded plugins:

**Comment by achedon12** [comment]
Good evening, sorry for the delay in replying, I just saw the bug and corrected it just now!
The plugin is back to work
For more info, go to my [github](https://github.com/achedon12)
